apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: app
          image: localhost:32000/crimson_grafana:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000