apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: app
          image: localhost:32000/crimson_prometheus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090