version: '3.7'

services:
  deployment_container:
    container_name: ansible_container_update
    image: deployment-container
    environment:
      DB_PASS: ${DATABASE_PASSWORD}
      DB_HOST: ${DATABASE_HOST:-database_container}
      DB_PORT: ${DATABASE_PORT:-5432}
      DB_USER: ${DATABASE_USER:-abstracto}
      DB_NAME: ${DATABASE_NAME:-abstracto}
      EXECUTE_DEPLOYMENT: 'true'
      EXECUTE_LIQUIBASE: ${EXECUTE_LIQUIBASE:-false}
      EXECUTE_TEMPLATES: ${EXECUTE_TEMPLATES:-true}
      LIQUIBASE_PATH: ${LIQUIBASE_PATH:-/liquibase}
      POSTGRES_DRIVER_PATH: ${EXECUTE_DEPLOYMENT:-/postgres/driver.jar}
    volumes:
      - ~/.m2/:/root/.m2
      - ./ansible/:/tmp/installer/ansible
    networks:
      - crimson


networks:
  crimson:
    external:
      name: crimson-network