version: '3.7'

services:
  db:
    image: postgres
    container_name: database_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: abstracto
      POSTGRES_USER: abstracto
  bot:
    image: docker.pkg.github.com/sheldan/crimson/crimson
    depends_on:
      - db
    restart: on-failure
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped