{
 "title": "Crimson status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Discord API Interaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(discord_api_interactions_total[1m])",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Commands processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(command_processed_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Message events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(message_total[1m])", "legendFormat": "{{ action }}" }
   ]
  },
  {
   "title": "HTTP Reponse codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(okhttp_request_total[1m])",
     "legendFormat": "{{ http_code }}"
    }
   ]
  },
  {
   "title": "Modmail messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(modmail_messges_total[1m])",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Starboard reactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starboard_stars_total[1m])",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Help command",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(help_executions_total[1m])",
     "legendFormat": "{{ category }}"
    }
   ]
  },
  {
   "title": "Assignable role actions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(assignable_roles_total[1m])",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Emote tracking",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(emote_usages_total[1m])",
     "legendFormat": "Used emotes"
    }
   ]
  },
  {
   "title": "Embedded messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(message_embedded_total[1m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Modmail threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(modmail_threads_total[1m])",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Invite filter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(invite_filter_total[1m])",
     "legendFormat": "{{ consequence }}"
    }
   ]
  },
  {
   "title": "Message purges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(moderation_purge_total[1m])",
     "legendFormat": "Messages"
    }
   ]
  }
 ]
}