name: Deploy bot to server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.PRIVATE_SSH }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-config/src/main/docker/docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}"